### ISSUE TITLE
Configure venv

### ISSUE THREAD

**Issue by dashmage** [babakks/vscode-juju-charmcraft-ide#15]
Hi, thanks for creating this super useful extension!

Is it possible to set up the python virtual environment at `.venv` instead of `venv`?

**Comment by babakks** [comment]
Hey,

I'm glad you found it useful.

Actually, as I remember, `venv` is the Charmcraft's preferred directory for virtual environment (for example, it's listed in `.gitignore`).

However, it's totally possible to keep the default behavior as is, but add some configuration parameter that allows overriding the virtual environment director


Actually, I hd this plan to provide some overrides via configuration, like this (in `.vscode/settings.json`):

```json
{
    "charmcraft-ide.overrides": {
        "*": {
             // New default for all charms
        },
        "path/to/charm": {
             // Charm-specific overrides
        }
    }
}
```

When that is implemented, which will be soon, we can also add a parameter to override the default `venv` directory.

How's that sound?

**Comment by dashmage** [comment]
An override for the default `venv` directory would be exactly what I was looking for!

**Comment by babakks** [comment]
@dashmage I just published the new version of the extension. It now supports some basic configurations and, of course, charm-specific overrides. You can find more details in the `README.md` (or the extension details page in VS Code).

In your case, if *all* charms in the workspace should use the same directory name (i.e., `.venv`) for the virtual environments, you can set it as a default in `.vscode/settings.json`, like this:

```jsonc
{
    "charmcraft-ide.defaultVirtualEnvDirectory": ".venv"
}
```

But, if you need to override the directory name just for a specific charm, then you'd need overrides:

```jsonc
{
   "charmcraft-ide.override": {
       "path/to/charm": {
            "virtualEnvDirectory": ".venv"
       }
   }
}
```

Hope this works for you. Thanks again for your good suggestion. :pray:

I close this issue now. If you found bugs in the new version, please comment here.
